#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../../../../config/environment'

#begin
p = Papa.new
p.save
  puts Papa.singleton_methods(false).include? 'original_table_name'
#rescue
  Entity.extend ToFile
  Entity.table_name
  Entity.to_file
#  raise
#end