#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment'

#begin
p = Papa.new
p.save
  puts Papa.singleton_methods(false).include? 'original_table_name'
#rescue
  Papa.extend ToFile
  Papa.to_file
#  raise
#end